#! /bin/sh

# Auto start #
sxhkd &
$HOME/.screenlayout/main.sh &
$HOME/.config/polybar/launch.sh &

# Monitor setup #
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 0

# Window styling #
bspc config top_padding        30
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       1
bspc config window_gap         6

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules #

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a pavucontrol state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
