#! /bin/sh

# Auto start #
sxhkd &
$HOME/.screenlayout/main.sh &

# Monitor setup #
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9

# Window styling #
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules #

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
